// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess
{
    public partial class Product
    {
        public Product()
        {
            SalesOrderDetails = new HashSet<SalesOrderDetail>();
        }

        [Key]
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        [Required]
        [StringLength(100)]
        public string ProductName { get; set; }
        [StringLength(500)]
        public string ProductDetail { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? SalesPrice { get; set; }
        [StringLength(200)]
        public string ImagePath { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty("Products")]
        public virtual Category Category { get; set; }
        [InverseProperty(nameof(SalesOrderDetail.Product))]
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
    }
}