// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess
{
    public partial class SalesOrderShipment
    {
        [Key]
        public int ShipmentId { get; set; }
        public int SalesOrderId { get; set; }
        [Required]
        [StringLength(250)]
        public string CustomerName { get; set; }
        [StringLength(250)]
        public string AddressLine1 { get; set; }
        [StringLength(250)]
        public string AddressLine2 { get; set; }
        [StringLength(50)]
        public string City { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }

        [ForeignKey(nameof(SalesOrderId))]
        [InverseProperty("SalesOrderShipments")]
        public virtual SalesOrder SalesOrder { get; set; }
    }
}