// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace DataAccess
{
    [Table("SalesOrderDetail")]
    public partial class SalesOrderDetail
    {
        [Key]
        [Column("SODetailId")]
        public int SodetailId { get; set; }
        public int SalesOrderId { get; set; }
        public int ProductId { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal Total { get; set; }

        [ForeignKey(nameof(ProductId))]
        [InverseProperty("SalesOrderDetails")]
        public virtual Product Product { get; set; }
        [ForeignKey(nameof(SalesOrderId))]
        [InverseProperty("SalesOrderDetails")]
        public virtual SalesOrder SalesOrder { get; set; }
    }
}